//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Journal = new HashSet<Journal>();
        }

        [Display(Name = "ID студента")]
        [Required(ErrorMessage = "Поле должно быть заполнено")]
        [RegularExpression(@"[0-9]{5,10}", ErrorMessage = "Некорректный ID студента")]
        public int ID { get; set; }

        [Display(Name = "Имя студента")]
        [Required(ErrorMessage = "Поле должно быть заполнено")]
        public string StudentName { get; set; }

        [Display(Name = "Адрес")]
        [Required(ErrorMessage = "Поле должно быть заполнено")]
        public string Adress { get; set; }

        [Display(Name = "Телефон")]
        [Required(ErrorMessage = "Поле должно быть заполнено")]
        [DataType(DataType.PhoneNumber)]
        [UIHint("String")]
        [RegularExpression(@"^\+?[78][-\(]?\d{3}\)?-?\d{3}-?\d{2}-?\d{2}$", ErrorMessage = "Некорректный номер телефона")]
        public Nullable<long> PhoneNumber { get; set; }

        [Display(Name = "Опекун")]
        [Required(ErrorMessage = "Поле должно быть заполнено")]
        public string Caretaker { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journal> Journal { get; set; }
    }
}
